/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.75
 * Generated at: 2022-05-05 12:40:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class head_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	<!-- header -->\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("	<meta name=\"author\" content=\"Untree.co\">\r\n");
      out.write("	<link rel=\"shortcut icon\" href=\"/resources/assets/homespace/favicon.png\">\r\n");
      out.write("	\r\n");
      out.write("	<meta name=\"description\" content=\"\" />\r\n");
      out.write("	<meta name=\"keywords\" content=\"bootstrap, bootstrap4, bootstrap5\" />\r\n");
      out.write("	\r\n");
      out.write("	<!-- theme: homespace -->\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Lato:wght@400;900&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/homespace/css/bootstrap.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/homespace/css/owl.carousel.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/homespace/css/owl.theme.default.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/homespace/css/jquery.fancybox.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/homespace/fonts/icomoon/style.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/homespace/fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/homespace/css/aos.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/homespace/css/style.css\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- theme: tour -->\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Source+Serif+Pro:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/tour/fonts/icomoon/style.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/tour/fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/tour/css/daterangepicker.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/tour/css/aos.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/tour/css/style.css\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- theme: blogy -->\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/blogy/fonts/icomoon/style.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/blogy/fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/blogy/css/tiny-slider.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/blogy/css/aos.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/blogy/css/glightbox.min.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/blogy/css/style.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/blogy/css/flatpickr.min.css\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- theme: property -->\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Work+Sans:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/property/fonts/icomoon/style.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/property/fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/property/css/tiny-slider.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/property/css/aos.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/assets/property/css/style.css\">");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
