/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.75
 * Generated at: 2022-05-05 13:11:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.pension;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/head.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<title>여수어때 : 상세페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"site-mobile-menu site-navbar-target\">\r\n");
      out.write("		<div class=\"site-mobile-menu-header\">\r\n");
      out.write("			<div class=\"site-mobile-menu-close\">\r\n");
      out.write("				<span class=\"icofont-close js-menu-toggle\"></span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"site-mobile-menu-body\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/nav.jsp", out, false);
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- 상세페이지 메인 -->\r\n");
      out.write("	<div class=\"section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-between\">\r\n");
      out.write("				<div class=\"col-lg-7\">\r\n");
      out.write("					<div class=\"img-property-slide-wrap\">\r\n");
      out.write("						<div class=\"img-property-slide\">\r\n");
      out.write("							<img src=\"/resources/assets/property/images/flag.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("							<img src=\"/resources/assets/property/images/flag2.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("							<img src=\"/resources/assets/property/images/flag3.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4\">\r\n");
      out.write("					<h2 class=\"heading text-primary\">여긴 내가 가져가겠다!</h2>\r\n");
      out.write("					<p class=\"meta\">-상남자-</p>\r\n");
      out.write("					<p class=\"text-black-50\">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ratione laborum quo quos omnis sed magnam id, ducimus saepe, debitis error earum, iste dicta odio est sint dolorem magni animi tenetur.</p>\r\n");
      out.write("					<p class=\"text-black-50\">Perferendis eligendi reprehenderit, assumenda molestias nisi eius iste reiciendis porro tenetur in, repudiandae amet libero. Doloremque, reprehenderit cupiditate error laudantium qui, esse quam debitis, eum cumque perferendis, illum harum expedita.</p>\r\n");
      out.write("					<div class=\"d-block agent-box p-5\">\r\n");
      out.write("						<div class=\"img mb-4\">\r\n");
      out.write("							<img src=\"/resources/assets/property/images/person_2.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"text\">\r\n");
      out.write("							<h3 class=\"mb-0\">Alicia Huston</h3>\r\n");
      out.write("							<div class=\"meta mb-3\">Real Estate</div>\r\n");
      out.write("							<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione laborum quo quos omnis sed magnam id ducimus saepe</p>\r\n");
      out.write("							<ul class=\"list-unstyled social dark-hover d-flex\">\r\n");
      out.write("								<li class=\"me-1\"><a href=\"#\"><span class=\"icon-instagram\"></span></a></li>\r\n");
      out.write("								<li class=\"me-1\"><a href=\"#\"><span class=\"icon-twitter\"></span></a></li>\r\n");
      out.write("								<li class=\"me-1\"><a href=\"#\"><span class=\"icon-facebook\"></span></a></li>\r\n");
      out.write("								<li class=\"me-1\"><a href=\"#\"><span class=\"icon-linkedin\"></span></a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<!-- 펜션 숙소 리스트 -->\r\n");
      out.write("	<div class=\"section\">\r\n");
      out.write("		<!-- 펜션 숙소 1 -->\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-between mb-5\">\r\n");
      out.write("				<div class=\"col-lg-7 mb-5 mb-lg-0 order-lg-2\">\r\n");
      out.write("					<img src=\"/resources/assets/property/images/hero_bg_3.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4\">\r\n");
      out.write("					<div class=\"d-flex feature-h\">\r\n");
      out.write("						<span class=\"wrap-icon me-3\">\r\n");
      out.write("							<span class=\"icon-home2\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("						<div class=\"feature-text\">\r\n");
      out.write("							<h3 class=\"heading\">Quality properties</h3>\r\n");
      out.write("							<p class=\"text-black-50\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum iste.</p>   \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"d-flex feature-h\">\r\n");
      out.write("						<span class=\"wrap-icon me-3\">\r\n");
      out.write("							<span class=\"icon-person\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("						<div class=\"feature-text\">\r\n");
      out.write("							<h3 class=\"heading\">Top rated agents</h3>\r\n");
      out.write("							<p class=\"text-black-50\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum iste.</p>   \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"d-flex feature-h\">\r\n");
      out.write("						<span class=\"wrap-icon me-3\">\r\n");
      out.write("							<span class=\"icon-security\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("						<div class=\"feature-text\">\r\n");
      out.write("							<h3 class=\"heading\">Easy and safe</h3>\r\n");
      out.write("							<p class=\"text-black-50\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum iste.</p>   \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 펜션 숙소 2 -->\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-between mb-5\">\r\n");
      out.write("				<div class=\"col-lg-7 mb-5 mb-lg-0\">\r\n");
      out.write("					<img src=\"/resources/assets/property/images/hero_bg_2.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4\">\r\n");
      out.write("					<div class=\"d-flex feature-h\">\r\n");
      out.write("						<span class=\"wrap-icon me-3\">\r\n");
      out.write("							<span class=\"icon-home2\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("						<div class=\"feature-text\">\r\n");
      out.write("							<h3 class=\"heading\">Quality properties</h3>\r\n");
      out.write("							<p class=\"text-black-50\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum iste.</p>   \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"d-flex feature-h\">\r\n");
      out.write("						<span class=\"wrap-icon me-3\">\r\n");
      out.write("							<span class=\"icon-person\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("						<div class=\"feature-text\">\r\n");
      out.write("							<h3 class=\"heading\">Top rated agents</h3>\r\n");
      out.write("							<p class=\"text-black-50\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum iste.</p>   \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"d-flex feature-h\">\r\n");
      out.write("						<span class=\"wrap-icon me-3\">\r\n");
      out.write("							<span class=\"icon-security\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("						<div class=\"feature-text\">\r\n");
      out.write("							<h3 class=\"heading\">Easy and safe</h3>\r\n");
      out.write("							<p class=\"text-black-50\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum iste.</p>   \r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<!-- 펜션 댓글 리스트 -->\r\n");
      out.write("	<div class=\"section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"comment-wrap\">\r\n");
      out.write("			<h3 class=\"mb-4 heading\">6 Comments</h3>\r\n");
      out.write("				<ul class=\"comment-list\">\r\n");
      out.write("					<!-- 댓글 1 -->\r\n");
      out.write("					<li class=\"comment border-bottom\">\r\n");
      out.write("						<div class=\"vcard\">\r\n");
      out.write("							<img src=\"/resources/assets/property/images/person_1.jpg\" alt=\"Image placeholder\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"comment-body\">\r\n");
      out.write("							<h3>댓글 1</h3>\r\n");
      out.write("							<div class=\"meta\">January 9, 2018 at 2:21pm</div>\r\n");
      out.write("							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<!-- 댓글 2 -->\r\n");
      out.write("					<li class=\"comment border-bottom\">\r\n");
      out.write("						<div class=\"vcard\">\r\n");
      out.write("							<img src=\"/resources/assets/property/images/person_2.jpg\" alt=\"Image placeholder\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"comment-body\">\r\n");
      out.write("							<h3>댓글 2</h3>\r\n");
      out.write("							<div class=\"meta\">January 9, 2018 at 2:21pm</div>\r\n");
      out.write("							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- 답글 -->\r\n");
      out.write("						<ul class=\"children\">\r\n");
      out.write("							<li class=\"comment\">\r\n");
      out.write("								<div class=\"vcard\">\r\n");
      out.write("									<img src=\"/resources/assets/property/images/person_3.jpg\" alt=\"Image placeholder\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"comment-body\">\r\n");
      out.write("									<h3>답글이다</h3>\r\n");
      out.write("									<div class=\"meta\">January 9, 2018 at 2:21pm</div>\r\n");
      out.write("									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<hr>\r\n");
      out.write("	<!-- 하단 펜션 이미지 -->\r\n");
      out.write("	<div class=\"container my-5\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-4\" data-aos=\"fade-up\" data-aos-delay=\"0\">\r\n");
      out.write("				<img src=\"/resources/assets/property/images/img_1.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-4 mt-lg-5\" data-aos=\"fade-up\" data-aos-delay=\"100\">\r\n");
      out.write("				<img src=\"/resources/assets/property/images/img_3.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-4\" data-aos=\"fade-up\" data-aos-delay=\"200\">\r\n");
      out.write("				<img src=\"/resources/assets/property/images/img_2.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
