/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.75
 * Generated at: 2022-05-05 12:39:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../views/common/head.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<title>여수어때 : 메인페이지</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"lines-wrap\">\r\n");
      out.write("		<div class=\"lines-inner\">\r\n");
      out.write("			<div class=\"lines\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"site-mobile-menu site-navbar-target\">\r\n");
      out.write("		<div class=\"site-mobile-menu-header\">\r\n");
      out.write("				<div class=\"site-mobile-menu-close\">\r\n");
      out.write("					<span class=\"icofont-close js-menu-toggle\"></span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		<div class=\"site-mobile-menu-body\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../views/common/nav.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("	<!-- 메인페이지 필터 -->\r\n");
      out.write("	<div class=\"hero\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row align-items-center\">\r\n");
      out.write("				<div class=\"col-lg-7\">\r\n");
      out.write("					<div class=\"intro-wrap\">\r\n");
      out.write("						<h1 class=\"mb-5\"><span class=\"d-block\">Let's Enjoy Your</span> Trip In <span class=\"typed-words\"></span></h1>\r\n");
      out.write("						<!-- 메인페이지 필터 시작 -->\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-12\">\r\n");
      out.write("								<form class=\"form\" action=\"/pension/list\">\r\n");
      out.write("									<div class=\"row mb-2\">\r\n");
      out.write("										<div class=\"col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-4\">\r\n");
      out.write("											<select name=\"\" id=\"\" class=\"form-control custom-select\">\r\n");
      out.write("												<option value=\"\">Destination</option>\r\n");
      out.write("												<option value=\"\">Peru</option>\r\n");
      out.write("												<option value=\"\">Japan</option>\r\n");
      out.write("												<option value=\"\">Thailand</option>\r\n");
      out.write("												<option value=\"\">Brazil</option>\r\n");
      out.write("												<option value=\"\">United States</option>\r\n");
      out.write("												<option value=\"\">Israel</option>\r\n");
      out.write("												<option value=\"\">China</option>\r\n");
      out.write("												<option value=\"\">Russia</option>\r\n");
      out.write("											</select>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-5\">\r\n");
      out.write("											<input type=\"text\" class=\"form-control\" name=\"daterange\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-3\">\r\n");
      out.write("											<input type=\"text\" class=\"form-control\" placeholder=\"# of People\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>    \r\n");
      out.write("									<div class=\"row align-items-center\">\r\n");
      out.write("										<div class=\"col-sm-12 col-md-6 mb-3 mb-lg-0 col-lg-4\">\r\n");
      out.write("											<input type=\"submit\" class=\"btn btn-primary btn-block\" value=\"Search\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"col-lg-8\">\r\n");
      out.write("											<label class=\"control control--checkbox mt-3\">\r\n");
      out.write("												<span class=\"caption\">Save this search</span>\r\n");
      out.write("												<input type=\"checkbox\" checked=\"checked\" />\r\n");
      out.write("												<div class=\"control__indicator\"></div>\r\n");
      out.write("											</label>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</form>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 필터 슬라이드 이미지 -->\r\n");
      out.write("				<div class=\"col-lg-5\">\r\n");
      out.write("					<div class=\"slides\">\r\n");
      out.write("						<img src=\"/resources/assets/tour/images/hero-slider-2.jpg\" alt=\"Image\" class=\"img-fluid active\">\r\n");
      out.write("						<img src=\"/resources/assets/tour/images/hero-slider-2.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("						<img src=\"/resources/assets/tour/images/hero-slider-2.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("						<img src=\"/resources/assets/tour/images/hero-slider-2.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("						<img src=\"/resources/assets/tour/images/hero-slider-2.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 펜션 목록 -->\r\n");
      out.write("	<div class=\"untree_co-section2 bg-light\">\r\n");
      out.write("		<!-- 이동 버튼 -->\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row align-items-center mb-3\">\r\n");
      out.write("				<div class=\"col-6\">\r\n");
      out.write("					<h2 class=\"heading-2\">Pensions</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-6 text-right properties-nav-direction\">\r\n");
      out.write("					<a href=\"#\" class=\"prev js-custom-prev-v2\"><span class=\"icon-keyboard_backspace\"></span></a>\r\n");
      out.write("					<a href=\"#\" class=\"next js-custom-next-v2\"><span class=\"icon-keyboard_backspace\"></span></a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 펜션 내용 -->\r\n");
      out.write("		<div class=\"owl-3-slider owl-carousel\">\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<div class=\"property-entry\">\r\n");
      out.write("					<img src=\"/resources/assets/homespace/images/property_2-min.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("					<div class=\"property-specs\">\r\n");
      out.write("						<strong class=\"price\">$900,295</strong>\r\n");
      out.write("						<ul class=\"list-unstyled specs\">\r\n");
      out.write("							<li class=\"d-inline-flex align-items-center\">\r\n");
      out.write("							<span class=\"icon-wrap flaticon-bathtub\"></span>\r\n");
      out.write("							<strong>2</strong>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li class=\"d-inline-flex align-items-center\">\r\n");
      out.write("							<span class=\"icon-wrap flaticon-bed\"></span>\r\n");
      out.write("							<strong>4</strong>\r\n");
      out.write("							</li>\r\n");
      out.write("							<li class=\"d-inline-flex align-items-center\">\r\n");
      out.write("							<span class=\"icon-wrap flaticon-house-size\"></span>\r\n");
      out.write("							<strong>120<sup>2</sup></strong>\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("						<div class=\"location d-flex justify-content-between align-items-center\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<span class=\"d-block caption\">location: </span>\r\n");
      out.write("								<h3><a href=\"#\"><span>2 Zwar Place, Florey</span></a></h3>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"more\">\r\n");
      out.write("								<a href=\"#\">\r\n");
      out.write("									<span class=\"icon-keyboard_backspace\"></span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>    \r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 펜션 광고 -->\r\n");
      out.write("	<div class=\"untree_co_slider-wrap\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row align-items-center mb-4\">\r\n");
      out.write("				<div class=\"col-6\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"nav-direction\">\r\n");
      out.write("			<a href=\"#\" class=\"js-nav-right nav-right\"><span class=\"icon-keyboard_arrow_right\"></span></a>\r\n");
      out.write("			<a href=\"#\" class=\"js-nav-left nav-left\"><span class=\"icon-keyboard_arrow_left\"></span></a>\r\n");
      out.write("		</div>\r\n");
      out.write("	\r\n");
      out.write("		<div class=\"untree_co_slider\">\r\n");
      out.write("			<!-- 펜션 1 -->\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<img src=\"/resources/assets/homespace/images/property_2-min.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("				<div class=\"property-contents\">\r\n");
      out.write("					<strong class=\"current-price text-secondary\">$999,000</strong>\r\n");
      out.write("					<span class=\"old-price\">$1,000,299</span>\r\n");
      out.write("					<h2>\r\n");
      out.write("						<a href=\"#\"><span>62/1 Braybrooke Street, Bruce</span></a>\r\n");
      out.write("					</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"property_details\">\r\n");
      out.write("					<ul class=\"list-unstyled specs\">\r\n");
      out.write("						<li class=\"d-inline-flex align-items-center\">\r\n");
      out.write("							<span class=\"icon-wrap flaticon-bathtub\"></span>\r\n");
      out.write("							<strong>2</strong>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"d-inline-flex align-items-center\">\r\n");
      out.write("							<span class=\"icon-wrap flaticon-bed\"></span>\r\n");
      out.write("							<strong>4</strong>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"d-inline-flex align-items-center\">\r\n");
      out.write("							<span class=\"icon-wrap flaticon-house-size\"></span>\r\n");
      out.write("							<strong>120<sup>2</sup></strong>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div> \r\n");
      out.write("			<!-- 펜션 2 -->\r\n");
      out.write("			<div class=\"item\">\r\n");
      out.write("				<img src=\"/resources/assets/homespace/images/property_3-min.jpg\" alt=\"Image\" class=\"img-fluid\">\r\n");
      out.write("				<div class=\"property-contents\">\r\n");
      out.write("					<strong class=\"current-price text-secondary\">$999,000</strong>\r\n");
      out.write("					<span class=\"old-price\">$1,000,299</span>\r\n");
      out.write("					<h2>\r\n");
      out.write("						<a href=\"#\"><span>32/13-15 Sturt Avenue, Griffith</span></a>\r\n");
      out.write("					</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"property_details\">\r\n");
      out.write("					<ul class=\"list-unstyled specs\">\r\n");
      out.write("						<li class=\"d-inline-flex align-items-center\">\r\n");
      out.write("							<span class=\"icon-wrap flaticon-bathtub\"></span>\r\n");
      out.write("							<strong>2</strong>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"d-inline-flex align-items-center\">\r\n");
      out.write("							<span class=\"icon-wrap flaticon-bed\"></span>\r\n");
      out.write("							<strong>4</strong>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li class=\"d-inline-flex align-items-center\">\r\n");
      out.write("							<span class=\"icon-wrap flaticon-house-size\"></span>\r\n");
      out.write("							<strong>120<sup>2</sup></strong>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div> \r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 최신 댓글 -->\r\n");
      out.write("	<div class=\"section sec-testimonials\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row mb-5 align-items-center\">\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<h2 class=\"font-weight-bold heading text-primary mb-4 mb-md-0\">Customer Says</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-6 text-md-end\">\r\n");
      out.write("					<div id=\"testimonial-nav\">\r\n");
      out.write("						<span class=\"prev\" data-controls=\"prev\">Prev</span>\r\n");
      out.write("						<span class=\"next\" data-controls=\"next\">Next</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg-4\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"testimonial-slider-wrap\">\r\n");
      out.write("			<div class=\"testimonial-slider\">\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<div class=\"testimonial\">\r\n");
      out.write("						<img src=\"/resources/assets/property/images/person_1.jpg\" alt=\"Image\" class=\"img-fluid rounded-circle w-25 mb-4\">\r\n");
      out.write("						<div class=\"rate\">\r\n");
      out.write("							<span class=\"icon-star text-warning\"></span>\r\n");
      out.write("							<span class=\"icon-star text-warning\"></span>\r\n");
      out.write("							<span class=\"icon-star text-warning\"></span>\r\n");
      out.write("							<span class=\"icon-star text-warning\"></span>\r\n");
      out.write("							<span class=\"icon-star text-warning\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<h3 class=\"h5 text-primary mb-4\">James Smith</h3>\r\n");
      out.write("						<blockquote>\r\n");
      out.write("							<p>&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;</p>\r\n");
      out.write("						</blockquote>\r\n");
      out.write("						<p class=\"text-black-50\">Designer, Co-founder</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<div class=\"testimonial\">\r\n");
      out.write("						<img src=\"/resources/assets/property/images/person_2.jpg\" alt=\"Image\" class=\"img-fluid rounded-circle w-25 mb-4\">\r\n");
      out.write("						<div class=\"rate\">\r\n");
      out.write("							<span class=\"icon-star text-warning\"></span>\r\n");
      out.write("							<span class=\"icon-star text-warning\"></span>\r\n");
      out.write("							<span class=\"icon-star text-warning\"></span>\r\n");
      out.write("							<span class=\"icon-star text-warning\"></span>\r\n");
      out.write("							<span class=\"icon-star text-warning\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<h3 class=\"h5 text-primary mb-4\">Mike Houston</h3>\r\n");
      out.write("						<blockquote>\r\n");
      out.write("							<p>&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;</p>\r\n");
      out.write("						</blockquote>\r\n");
      out.write("						<p class=\"text-black-50\">Designer, Co-founder</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 카운트 -->\r\n");
      out.write("	<div class=\"text-center\">\r\n");
      out.write("		<div class=\"row section-counter my-5\">\r\n");
      out.write("			<div class=\"col-6 col-sm-6 col-md-6 col-lg-3\" data-aos-delay=\"300\">\r\n");
      out.write("				<div class=\"counter-wrap mb-5 mb-lg-0\">\r\n");
      out.write("					<span class=\"number\"><span class=\"countup text-primary\">2917</span></span>\r\n");
      out.write("					<span class=\"caption text-black-50\"># of Buy Properties</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-6 col-sm-6 col-md-6 col-lg-3\" data-aos-delay=\"400\">\r\n");
      out.write("				<div class=\"counter-wrap mb-5 mb-lg-0\">\r\n");
      out.write("					<span class=\"number\"><span class=\"countup text-primary\">3918</span></span>\r\n");
      out.write("					<span class=\"caption text-black-50\"># of Sell Properties</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-6 col-sm-6 col-md-6 col-lg-3\" data-aos-delay=\"500\">\r\n");
      out.write("				<div class=\"counter-wrap mb-5 mb-lg-0\">\r\n");
      out.write("					<span class=\"number\"><span class=\"countup text-primary\">38928</span></span>\r\n");
      out.write("					<span class=\"caption text-black-50\"># of All Properties</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-6 col-sm-6 col-md-6 col-lg-3\" data-aos-delay=\"600\">\r\n");
      out.write("				<div class=\"counter-wrap mb-5 mb-lg-0\">\r\n");
      out.write("					<span class=\"number\"><span class=\"countup text-primary\">1291</span></span>\r\n");
      out.write("					<span class=\"caption text-black-50\"># of Agents</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function() {\r\n");
      out.write("			var slides = $('.slides'),\r\n");
      out.write("			images = slides.find('img');\r\n");
      out.write("			\r\n");
      out.write("			images.each(function(i) {\r\n");
      out.write("				$(this).attr('data-id', i + 1);\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("			var typed = new Typed('.typed-words', {\r\n");
      out.write("				strings: [\" 김동엽 바보\",\"  상남자 상현\",\" 이거는\", \" 여수어때\", \" 여수오때아님\"],\r\n");
      out.write("				typeSpeed: 80,\r\n");
      out.write("				backSpeed: 80,\r\n");
      out.write("				backDelay: 4000,\r\n");
      out.write("				startDelay: 1000,\r\n");
      out.write("				loop: true,\r\n");
      out.write("				showCursor: true,\r\n");
      out.write("				preStringTyped: (arrayPos, self) => {\r\n");
      out.write("					arrayPos++;\r\n");
      out.write("					console.log(arrayPos);\r\n");
      out.write("					$('.slides img').removeClass('active');\r\n");
      out.write("					$('.slides img[data-id=\"'+arrayPos+'\"]').addClass('active');\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
